### PR TITLE
#175261546 sort and remove expired offers from active route

### PR DESCRIPTION
**Pull request by tobieeniafe**
#### What does this PR do?
Sort and remove expired offers from active route

#### Description of Task to be completed?
Sort and remove expired offers from active route

#### How should this be manually tested?
`GET /api/v1/offer/active`

#### What are the relevant pivotal tracker stories?
#175261546

### CODE REVIEW

**Review by andela-hpopoola — CHANGES_REQUESTED** [review]
Thank you for working on this. We need to add one more test before merging. 

You need to add 3 active offers with the expire date not sorted and see that they are sorted by date when they are returned.

**Review by andela-hpopoola — DISMISSED** [review]
Thank you for working on this. Even though the test looks a bit difficult to read because of the ordered numbering, other suggestions might make it more cumbersome and waste more time -- so I am approving this PR.

Kindly fix the failing tests so that I can approve this.

**Comment by tobieeniafe** [comment]
> Thank you for working on this. Even though the test looks a bit difficult to read because of the ordered numbering, other suggestions might make it more cumbersome and waste more time -- so I am approving this PR.
> 
> Kindly fix the failing tests so that I can approve this.

I don't understand what's happening, but the test pass locally, but keep failing on travis

**Review by andela-hpopoola — CHANGES_REQUESTED** [review]
I am also not sure what the issue could be as the latest code on develop branch currently pass the Travis test. The problem is that we can't merge this if the tests are still failing and I am currently not in the best state to investigate.

**Comment by andela-hpopoola** [comment]
@tobieeniafe, it looks like I might have resolved the failing tests. Can you rebase this PR to the latest version of develop and push the updated code here to ensure that this test pass too?

**Review by andela-hpopoola — APPROVED** [review]
Thank you for updating this. Feel free to merge this when ready.

**Pull request merged**
